//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDBDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public Students()
        {
            this.ScoreList = new HashSet<ScoreList>();
        }    
        public int StudentId { get; set; }
        public string StudentName { get; set; }
        public string Gender { get; set; }
        public System.DateTime Birthday { get; set; }
        public decimal StudentIdNo { get; set; }
        public int Age { get; set; }
        public string PhoneNumber { get; set; }
        public string StudentAddress { get; set; }
        public int ClassId { get; set; }
    
        public virtual ICollection<ScoreList> ScoreList { get; set; }
        public virtual StudentClass StudentClass { get; set; }
    }
}
