//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOA.UnitTest8.advaned8.WS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="advaned8.WS.WSDemoSoap")]
    public interface WSDemoSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        SOA.UnitTest8.advaned8.WS.HelloWorldResponse HelloWorld(SOA.UnitTest8.advaned8.WS.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<SOA.UnitTest8.advaned8.WS.HelloWorldResponse> HelloWorldAsync(SOA.UnitTest8.advaned8.WS.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldIntResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorldInt", ReplyAction="*")]
        SOA.UnitTest8.advaned8.WS.HelloWorldIntResponse HelloWorldInt(SOA.UnitTest8.advaned8.WS.HelloWorldIntRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorldInt", ReplyAction="*")]
        System.Threading.Tasks.Task<SOA.UnitTest8.advaned8.WS.HelloWorldIntResponse> HelloWorldIntAsync(SOA.UnitTest8.advaned8.WS.HelloWorldIntRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public SOA.UnitTest8.advaned8.WS.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(SOA.UnitTest8.advaned8.WS.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public SOA.UnitTest8.advaned8.WS.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(SOA.UnitTest8.advaned8.WS.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldIntRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldInt", Namespace="http://tempuri.org/", Order=0)]
        public SOA.UnitTest8.advaned8.WS.HelloWorldIntRequestBody Body;
        
        public HelloWorldIntRequest() {
        }
        
        public HelloWorldIntRequest(SOA.UnitTest8.advaned8.WS.HelloWorldIntRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldIntRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int i;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int k;
        
        public HelloWorldIntRequestBody() {
        }
        
        public HelloWorldIntRequestBody(int i, int k) {
            this.i = i;
            this.k = k;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldIntResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldIntResponse", Namespace="http://tempuri.org/", Order=0)]
        public SOA.UnitTest8.advaned8.WS.HelloWorldIntResponseBody Body;
        
        public HelloWorldIntResponse() {
        }
        
        public HelloWorldIntResponse(SOA.UnitTest8.advaned8.WS.HelloWorldIntResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldIntResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldIntResult;
        
        public HelloWorldIntResponseBody() {
        }
        
        public HelloWorldIntResponseBody(string HelloWorldIntResult) {
            this.HelloWorldIntResult = HelloWorldIntResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSDemoSoapChannel : SOA.UnitTest8.advaned8.WS.WSDemoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSDemoSoapClient : System.ServiceModel.ClientBase<SOA.UnitTest8.advaned8.WS.WSDemoSoap>, SOA.UnitTest8.advaned8.WS.WSDemoSoap {
        
        public WSDemoSoapClient() {
        }
        
        public WSDemoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSDemoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSDemoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSDemoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOA.UnitTest8.advaned8.WS.HelloWorldResponse SOA.UnitTest8.advaned8.WS.WSDemoSoap.HelloWorld(SOA.UnitTest8.advaned8.WS.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            SOA.UnitTest8.advaned8.WS.HelloWorldRequest inValue = new SOA.UnitTest8.advaned8.WS.HelloWorldRequest();
            inValue.Body = new SOA.UnitTest8.advaned8.WS.HelloWorldRequestBody();
            SOA.UnitTest8.advaned8.WS.HelloWorldResponse retVal = ((SOA.UnitTest8.advaned8.WS.WSDemoSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOA.UnitTest8.advaned8.WS.HelloWorldResponse> SOA.UnitTest8.advaned8.WS.WSDemoSoap.HelloWorldAsync(SOA.UnitTest8.advaned8.WS.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOA.UnitTest8.advaned8.WS.HelloWorldResponse> HelloWorldAsync() {
            SOA.UnitTest8.advaned8.WS.HelloWorldRequest inValue = new SOA.UnitTest8.advaned8.WS.HelloWorldRequest();
            inValue.Body = new SOA.UnitTest8.advaned8.WS.HelloWorldRequestBody();
            return ((SOA.UnitTest8.advaned8.WS.WSDemoSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOA.UnitTest8.advaned8.WS.HelloWorldIntResponse SOA.UnitTest8.advaned8.WS.WSDemoSoap.HelloWorldInt(SOA.UnitTest8.advaned8.WS.HelloWorldIntRequest request) {
            return base.Channel.HelloWorldInt(request);
        }
        
        public string HelloWorldInt(int i, int k) {
            SOA.UnitTest8.advaned8.WS.HelloWorldIntRequest inValue = new SOA.UnitTest8.advaned8.WS.HelloWorldIntRequest();
            inValue.Body = new SOA.UnitTest8.advaned8.WS.HelloWorldIntRequestBody();
            inValue.Body.i = i;
            inValue.Body.k = k;
            SOA.UnitTest8.advaned8.WS.HelloWorldIntResponse retVal = ((SOA.UnitTest8.advaned8.WS.WSDemoSoap)(this)).HelloWorldInt(inValue);
            return retVal.Body.HelloWorldIntResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOA.UnitTest8.advaned8.WS.HelloWorldIntResponse> SOA.UnitTest8.advaned8.WS.WSDemoSoap.HelloWorldIntAsync(SOA.UnitTest8.advaned8.WS.HelloWorldIntRequest request) {
            return base.Channel.HelloWorldIntAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOA.UnitTest8.advaned8.WS.HelloWorldIntResponse> HelloWorldIntAsync(int i, int k) {
            SOA.UnitTest8.advaned8.WS.HelloWorldIntRequest inValue = new SOA.UnitTest8.advaned8.WS.HelloWorldIntRequest();
            inValue.Body = new SOA.UnitTest8.advaned8.WS.HelloWorldIntRequestBody();
            inValue.Body.i = i;
            inValue.Body.k = k;
            return ((SOA.UnitTest8.advaned8.WS.WSDemoSoap)(this)).HelloWorldIntAsync(inValue);
        }
    }
}
