//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhibernateShow.Model
{
    using System;
    using System.Collections.Generic;

    public class Commodity : BaseModel
    {
        public virtual Nullable<long> ProductId { get; set; }
        public virtual Nullable<int> CategoryId { get; set; }
        public virtual string Title { get; set; }
        public virtual Nullable<decimal> Price { get; set; }
        public virtual string Url { get; set; }
        public virtual string ImageUrl { get; set; }
    }

    //dal
}
