//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESTM.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ROLE
    {
        public TB_ROLE()
        {
            this.TB_MENUROLE = new HashSet<TB_MENUROLE>();
            this.TB_USERROLE = new HashSet<TB_USERROLE>();
        }
    
        public string ROLE_ID { get; set; }
        public string ROLE_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<System.DateTime> MODIFYTIME { get; set; }
        public string ROLE_DEFAULTURL { get; set; }
    
        public virtual ICollection<TB_MENUROLE> TB_MENUROLE { get; set; }
        public virtual ICollection<TB_USERROLE> TB_USERROLE { get; set; }
    }
}
