//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESTM.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USERS
    {
        public TB_USERS()
        {
            this.TB_USERROLE = new HashSet<TB_USERROLE>();
        }
    
        public string USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string USER_PASSWORD { get; set; }
        public string FULLNAME { get; set; }
        public string DEPARTMENT_ID { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<System.DateTime> MODIFYTIME { get; set; }
        public string REMARK { get; set; }
    
        public virtual TB_DEPARTMENT TB_DEPARTMENT { get; set; }
        public virtual ICollection<TB_USERROLE> TB_USERROLE { get; set; }
    }
}
