//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOA.UnitTest.MyWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebServiceUser", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class WebServiceUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private int AgeField;
        
        private int SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Sex {
            get {
                return this.SexField;
            }
            set {
                if ((this.SexField.Equals(value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyWebService.MyWebServiceSoap")]
    public interface MyWebServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        SOA.UnitTest.MyWebService.HelloWorldResponse HelloWorld(SOA.UnitTest.MyWebService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<SOA.UnitTest.MyWebService.HelloWorldResponse> HelloWorldAsync(SOA.UnitTest.MyWebService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Minus", ReplyAction="*")]
        int Minus(int iValueOne, int iValueTwo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Minus", ReplyAction="*")]
        System.Threading.Tasks.Task<int> MinusAsync(int iValueOne, int iValueTwo);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetUserResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUser", ReplyAction="*")]
        SOA.UnitTest.MyWebService.GetUserResponse GetUser(SOA.UnitTest.MyWebService.GetUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUser", ReplyAction="*")]
        System.Threading.Tasks.Task<SOA.UnitTest.MyWebService.GetUserResponse> GetUserAsync(SOA.UnitTest.MyWebService.GetUserRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 UserListResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserList", ReplyAction="*")]
        SOA.UnitTest.MyWebService.UserListResponse UserList(SOA.UnitTest.MyWebService.UserListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserList", ReplyAction="*")]
        System.Threading.Tasks.Task<SOA.UnitTest.MyWebService.UserListResponse> UserListAsync(SOA.UnitTest.MyWebService.UserListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public SOA.UnitTest.MyWebService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(SOA.UnitTest.MyWebService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public SOA.UnitTest.MyWebService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(SOA.UnitTest.MyWebService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUser", Namespace="http://tempuri.org/", Order=0)]
        public SOA.UnitTest.MyWebService.GetUserRequestBody Body;
        
        public GetUserRequest() {
        }
        
        public GetUserRequest(SOA.UnitTest.MyWebService.GetUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetUserRequestBody() {
        }
        
        public GetUserRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public SOA.UnitTest.MyWebService.GetUserResponseBody Body;
        
        public GetUserResponse() {
        }
        
        public GetUserResponse(SOA.UnitTest.MyWebService.GetUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SOA.UnitTest.MyWebService.WebServiceUser GetUserResult;
        
        public GetUserResponseBody() {
        }
        
        public GetUserResponseBody(SOA.UnitTest.MyWebService.WebServiceUser GetUserResult) {
            this.GetUserResult = GetUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserList", Namespace="http://tempuri.org/", Order=0)]
        public SOA.UnitTest.MyWebService.UserListRequestBody Body;
        
        public UserListRequest() {
        }
        
        public UserListRequest(SOA.UnitTest.MyWebService.UserListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UserListRequestBody {
        
        public UserListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserListResponse", Namespace="http://tempuri.org/", Order=0)]
        public SOA.UnitTest.MyWebService.UserListResponseBody Body;
        
        public UserListResponse() {
        }
        
        public UserListResponse(SOA.UnitTest.MyWebService.UserListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UserListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<SOA.UnitTest.MyWebService.WebServiceUser> UserListResult;
        
        public UserListResponseBody() {
        }
        
        public UserListResponseBody(System.Collections.Generic.List<SOA.UnitTest.MyWebService.WebServiceUser> UserListResult) {
            this.UserListResult = UserListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyWebServiceSoapChannel : SOA.UnitTest.MyWebService.MyWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyWebServiceSoapClient : System.ServiceModel.ClientBase<SOA.UnitTest.MyWebService.MyWebServiceSoap>, SOA.UnitTest.MyWebService.MyWebServiceSoap {
        
        public MyWebServiceSoapClient() {
        }
        
        public MyWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOA.UnitTest.MyWebService.HelloWorldResponse SOA.UnitTest.MyWebService.MyWebServiceSoap.HelloWorld(SOA.UnitTest.MyWebService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            SOA.UnitTest.MyWebService.HelloWorldRequest inValue = new SOA.UnitTest.MyWebService.HelloWorldRequest();
            inValue.Body = new SOA.UnitTest.MyWebService.HelloWorldRequestBody();
            SOA.UnitTest.MyWebService.HelloWorldResponse retVal = ((SOA.UnitTest.MyWebService.MyWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOA.UnitTest.MyWebService.HelloWorldResponse> SOA.UnitTest.MyWebService.MyWebServiceSoap.HelloWorldAsync(SOA.UnitTest.MyWebService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOA.UnitTest.MyWebService.HelloWorldResponse> HelloWorldAsync() {
            SOA.UnitTest.MyWebService.HelloWorldRequest inValue = new SOA.UnitTest.MyWebService.HelloWorldRequest();
            inValue.Body = new SOA.UnitTest.MyWebService.HelloWorldRequestBody();
            return ((SOA.UnitTest.MyWebService.MyWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public int Minus(int iValueOne, int iValueTwo) {
            return base.Channel.Minus(iValueOne, iValueTwo);
        }
        
        public System.Threading.Tasks.Task<int> MinusAsync(int iValueOne, int iValueTwo) {
            return base.Channel.MinusAsync(iValueOne, iValueTwo);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOA.UnitTest.MyWebService.GetUserResponse SOA.UnitTest.MyWebService.MyWebServiceSoap.GetUser(SOA.UnitTest.MyWebService.GetUserRequest request) {
            return base.Channel.GetUser(request);
        }
        
        public SOA.UnitTest.MyWebService.WebServiceUser GetUser(int id) {
            SOA.UnitTest.MyWebService.GetUserRequest inValue = new SOA.UnitTest.MyWebService.GetUserRequest();
            inValue.Body = new SOA.UnitTest.MyWebService.GetUserRequestBody();
            inValue.Body.id = id;
            SOA.UnitTest.MyWebService.GetUserResponse retVal = ((SOA.UnitTest.MyWebService.MyWebServiceSoap)(this)).GetUser(inValue);
            return retVal.Body.GetUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOA.UnitTest.MyWebService.GetUserResponse> SOA.UnitTest.MyWebService.MyWebServiceSoap.GetUserAsync(SOA.UnitTest.MyWebService.GetUserRequest request) {
            return base.Channel.GetUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOA.UnitTest.MyWebService.GetUserResponse> GetUserAsync(int id) {
            SOA.UnitTest.MyWebService.GetUserRequest inValue = new SOA.UnitTest.MyWebService.GetUserRequest();
            inValue.Body = new SOA.UnitTest.MyWebService.GetUserRequestBody();
            inValue.Body.id = id;
            return ((SOA.UnitTest.MyWebService.MyWebServiceSoap)(this)).GetUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOA.UnitTest.MyWebService.UserListResponse SOA.UnitTest.MyWebService.MyWebServiceSoap.UserList(SOA.UnitTest.MyWebService.UserListRequest request) {
            return base.Channel.UserList(request);
        }
        
        public System.Collections.Generic.List<SOA.UnitTest.MyWebService.WebServiceUser> UserList() {
            SOA.UnitTest.MyWebService.UserListRequest inValue = new SOA.UnitTest.MyWebService.UserListRequest();
            inValue.Body = new SOA.UnitTest.MyWebService.UserListRequestBody();
            SOA.UnitTest.MyWebService.UserListResponse retVal = ((SOA.UnitTest.MyWebService.MyWebServiceSoap)(this)).UserList(inValue);
            return retVal.Body.UserListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOA.UnitTest.MyWebService.UserListResponse> SOA.UnitTest.MyWebService.MyWebServiceSoap.UserListAsync(SOA.UnitTest.MyWebService.UserListRequest request) {
            return base.Channel.UserListAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOA.UnitTest.MyWebService.UserListResponse> UserListAsync() {
            SOA.UnitTest.MyWebService.UserListRequest inValue = new SOA.UnitTest.MyWebService.UserListRequest();
            inValue.Body = new SOA.UnitTest.MyWebService.UserListRequestBody();
            return ((SOA.UnitTest.MyWebService.MyWebServiceSoap)(this)).UserListAsync(inValue);
        }
    }
}
